const std = @import("std");
const nums = @import("kernel/syscall_numbers.zig");

const Entry = struct {
    symbol: []const u8,
    nr: usize,
};

fn emitEntry(file: std.fs.File, alloc: std.mem.Allocator, e: Entry) !void {
    const text = try std.fmt.allocPrint(
        alloc,
        ".global {s}\n{s}:\n li a7, {d}\n ecall\n ret\n",
        .{ e.symbol, e.symbol, e.nr },
    );
    defer alloc.free(text);
    try file.writeAll(text);
}

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const alloc = gpa.allocator();

    const argv = try std.process.argsAlloc(alloc);
    defer std.process.argsFree(alloc, argv);
    if (argv.len != 2) {
        std.debug.print("usage: gen_usys.zig <out-usys.S>\n", .{});
        return error.InvalidArgs;
    }

    var out = try std.fs.cwd().createFile(argv[1], .{ .truncate = true });
    defer out.close();
    try out.writeAll("# generated by gen_usys.zig - do not edit\n");

    const entries = [_]Entry{
        .{ .symbol = "fork", .nr = nums.SYS_fork },
        .{ .symbol = "exit", .nr = nums.SYS_exit },
        .{ .symbol = "wait", .nr = nums.SYS_wait },
        .{ .symbol = "pipe", .nr = nums.SYS_pipe },
        .{ .symbol = "read", .nr = nums.SYS_read },
        .{ .symbol = "write", .nr = nums.SYS_write },
        .{ .symbol = "close", .nr = nums.SYS_close },
        .{ .symbol = "kill", .nr = nums.SYS_kill },
        .{ .symbol = "exec", .nr = nums.SYS_exec },
        .{ .symbol = "open", .nr = nums.SYS_open },
        .{ .symbol = "mknod", .nr = nums.SYS_mknod },
        .{ .symbol = "unlink", .nr = nums.SYS_unlink },
        .{ .symbol = "fstat", .nr = nums.SYS_fstat },
        .{ .symbol = "link", .nr = nums.SYS_link },
        .{ .symbol = "mkdir", .nr = nums.SYS_mkdir },
        .{ .symbol = "chdir", .nr = nums.SYS_chdir },
        .{ .symbol = "dup", .nr = nums.SYS_dup },
        .{ .symbol = "getpid", .nr = nums.SYS_getpid },
        .{ .symbol = "sys_sbrk", .nr = nums.SYS_sbrk },
        .{ .symbol = "pause", .nr = nums.SYS_pause },
        .{ .symbol = "uptime", .nr = nums.SYS_uptime },
    };

    for (entries) |e| {
        try emitEntry(out, alloc, e);
    }
}
